### ISSUE TITLE
missing database file

### ISSUE THREAD

**Issue by aditya-ck** [alkboda/Downwork-Notifier#1]
we can not find the database file "Downwork.sdf" in the code folder.

**Comment by alkboda** [comment]
Hi, I added clean db file into solution and new self signed certificate which is valid until 2040. Tell me if something's wrong.
HTH

**Comment by aditya-ck** [comment]
Thanks, its working well.
can we use  SQL server 2008/later database? if possible, please suggest. 
Thanks in advance.

**Comment by alkboda** [comment]
Sorry for delay, I'm on vacation now.
You can use any appropriate database, which could be used with EF7, but now project is set for using MS SQL CE up.
You can find all available EF7 providers [here](https://docs.microsoft.com/en-us/ef/core/providers/)

**Comment by aditya-ck** [comment]
Thanks for guidance, now I have changed the project targeting SQL server . 
Now, I am trying to do job filter with multiple 'Category/Sub-Category' and 'Country Location'. As, i am novice to WPF. I am trying to replace two category/sub-category listboxes with single tree-view control. So that it can select multiple category/sub-categories.

Please help to do these changes in code
