### ISSUE TITLE
it's not working

### ISSUE THREAD

**Issue by sujit1779** [alkboda/Downwork-Notifier#2]
When I put down my keys, it doesn't work. Simply says failed.

**Comment by alkboda** [comment]
Hello,
can you describe more precisely your actions step by step? Did you grant access to the application in your upworks API profile? I'll take a look for precise steps at home.

**Comment by sujit1779** [comment]
Hi,

Sorry my fault. I am able to use it now, thanks for the good work.

Thanks

[image: Better Technology Labs]  <https://htmlsig.com/t/000001C5ACQF>


*Sujit Kumar Singh*Passionate Software Developer

sujit1779@gmail.com / (+91) 99 233 10606
Pune (India)
https://www.techsujit.com

/p>
